# Generated by Django 2.2.2 on 2020-02-04 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acquired_terminology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lemma', models.CharField(blank=True, max_length=256, null=True)),
                ('Acronimo', models.CharField(blank=True, max_length=25, null=True)),
                ('Definizione', models.TextField(blank=True, null=True)),
                ('Ambito_riferimento', models.CharField(blank=True, max_length=256, null=True)),
                ('Autore_definizione', models.TextField(blank=True, null=True)),
                ('Posizione_definizione', models.TextField(blank=True, null=True)),
                ('Url_definizione', models.URLField(blank=True, max_length=400, null=True)),
                ('Titolo_documento_fonte', models.TextField(blank=True, null=True)),
                ('Autore_documento_fonte', models.TextField(blank=True, null=True)),
                ('Host_documento_fonte', models.TextField(blank=True, null=True)),
                ('Url_documento_fonte', models.URLField(blank=True, max_length=400, null=True)),
                ('Commento_entry', models.TextField(blank=True, null=True)),
                ('Data_inserimento_entry', models.DateField(default=django.utils.timezone.now)),
                ('Id_statico_entry', models.CharField(default='ITCH00000', max_length=256)),
                ('Admin_approval_switch', models.CharField(choices=[('show', 'show'), ('hide', 'hide')], default=('hide', 'hide'), max_length=30)),
            ],
            options={
                'ordering': ['Admin_approval_switch', 'Lemma', 'Data_inserimento_entry', 'Id_statico_entry'],
            },
        ),
        migrations.CreateModel(
            name='glossary_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lemma', models.CharField(blank=True, max_length=256, null=True)),
                ('Acronimo', models.CharField(blank=True, max_length=25, null=True)),
                ('Definizione', models.TextField(blank=True, null=True)),
                ('Ambito_riferimento', models.CharField(blank=True, max_length=256, null=True)),
                ('Autore_definizione', models.TextField(blank=True, null=True)),
                ('Posizione_definizione', models.TextField(blank=True, null=True)),
                ('Url_definizione', models.URLField(blank=True, max_length=400, null=True)),
                ('Titolo_documento_fonte', models.TextField(blank=True, null=True)),
                ('Autore_documento_fonte', models.TextField(blank=True, null=True)),
                ('Host_documento_fonte', models.TextField(blank=True, null=True)),
                ('Url_documento_fonte', models.URLField(blank=True, max_length=400, null=True)),
                ('Commento_entry', models.TextField(blank=True, null=True)),
                ('Data_inserimento_entry', models.DateField(default=django.utils.timezone.now)),
                ('Id_statico_entry', models.CharField(default='ITCH00000', max_length=256)),
                ('Admin_approval_switch', models.CharField(choices=[('show', 'show'), ('hide', 'hide')], default=('hide', 'hide'), max_length=30)),
            ],
            options={
                'ordering': ['Admin_approval_switch', 'Lemma', 'Data_inserimento_entry', 'Id_statico_entry'],
            },
        ),
        migrations.CreateModel(
            name='glossary_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Glossary_file', models.FileField(upload_to='uploaded_glossaries/')),
                ('Data_inserimento_glossary', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['Data_inserimento_glossary', 'Glossary_file'],
            },
        ),
        migrations.CreateModel(
            name='model_is_acronimo_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_soggetto', models.CharField(max_length=10)),
                ('id_oggetto', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['id_soggetto', 'id_oggetto'],
            },
        ),
        migrations.CreateModel(
            name='model_is_admin_approval_switch_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_soggetto', models.CharField(max_length=10)),
                ('id_oggetto', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['id_soggetto', 'id_oggetto'],
            },
        ),
        migrations.CreateModel(
            name='model_is_ambito_riferimento_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_soggetto', models.CharField(max_length=10)),
                ('id_oggetto', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['id_soggetto', 'id_oggetto'],
            },
        ),
        migrations.CreateModel(
            name='model_is_autore_definizione_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_soggetto', models.CharField(max_length=10)),
                ('id_oggetto', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['id_soggetto', 'id_oggetto'],
            },
        ),
        migrations.CreateModel(
            name='model_is_autore_documento_fonte_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_soggetto', models.CharField(max_length=10)),
                ('id_oggetto', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['id_soggetto', 'id_oggetto'],
            },
        ),
        migrations.CreateModel(
            name='model_is_commento_entry_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_soggetto', models.CharField(max_length=10)),
                ('id_oggetto', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['id_soggetto', 'id_oggetto'],
            },
        ),
        migrations.CreateModel(
            name='model_is_data_inserimento_entry_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_soggetto', models.CharField(max_length=10)),
                ('id_oggetto', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['id_soggetto', 'id_oggetto'],
            },
        ),
        migrations.CreateModel(
            name='model_is_host_documento_fonte_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_soggetto', models.CharField(max_length=10)),
                ('id_oggetto', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['id_soggetto', 'id_oggetto'],
            },
        ),
        migrations.CreateModel(
            name='model_is_id_statico_entry_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_soggetto', models.CharField(max_length=10)),
                ('id_oggetto', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['id_soggetto', 'id_oggetto'],
            },
        ),
        migrations.CreateModel(
            name='model_is_lemma_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_soggetto', models.CharField(max_length=10)),
                ('id_oggetto', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['id_soggetto', 'id_oggetto'],
            },
        ),
        migrations.CreateModel(
            name='model_is_posizione_definizione_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_soggetto', models.CharField(max_length=10)),
                ('id_oggetto', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['id_soggetto', 'id_oggetto'],
            },
        ),
        migrations.CreateModel(
            name='model_is_titolo_documento_fonte_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_soggetto', models.CharField(max_length=10)),
                ('id_oggetto', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['id_soggetto', 'id_oggetto'],
            },
        ),
        migrations.CreateModel(
            name='model_is_url_definizione_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_soggetto', models.CharField(max_length=10)),
                ('id_oggetto', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['id_soggetto', 'id_oggetto'],
            },
        ),
        migrations.CreateModel(
            name='model_is_url_documento_fonte_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_soggetto', models.CharField(max_length=10)),
                ('id_oggetto', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['id_soggetto', 'id_oggetto'],
            },
        ),
        migrations.CreateModel(
            name='model_things',
            fields=[
                ('id_thing', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('thing', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id_thing', 'thing'],
            },
        ),
        migrations.CreateModel(
            name='prepared_terminology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lemma', models.CharField(blank=True, max_length=256, null=True)),
                ('Acronimo', models.CharField(blank=True, max_length=25, null=True)),
                ('Definizione', models.TextField(blank=True, null=True)),
                ('Ambito_riferimento', models.CharField(blank=True, max_length=256, null=True)),
                ('Autore_definizione', models.TextField(blank=True, null=True)),
                ('Posizione_definizione', models.TextField(blank=True, null=True)),
                ('Url_definizione', models.URLField(blank=True, max_length=400, null=True)),
                ('Titolo_documento_fonte', models.TextField(blank=True, null=True)),
                ('Autore_documento_fonte', models.TextField(blank=True, null=True)),
                ('Host_documento_fonte', models.TextField(blank=True, null=True)),
                ('Url_documento_fonte', models.URLField(blank=True, max_length=400, null=True)),
                ('Commento_entry', models.TextField(blank=True, null=True)),
                ('Data_inserimento_entry', models.DateField(default=django.utils.timezone.now)),
                ('Id_statico_entry', models.CharField(default='ITCH00000', max_length=256)),
                ('Admin_approval_switch', models.CharField(choices=[('show', 'show'), ('hide', 'hide')], default=('hide', 'hide'), max_length=30)),
            ],
            options={
                'ordering': ['Admin_approval_switch', 'Lemma', 'Data_inserimento_entry', 'Id_statico_entry'],
            },
        ),
    ]
